### ISSUE TITLE
DB Migration

### ISSUE THREAD

**Issue by afikrim** [shafaalafghany/bcc-intern#1]
Ini ada migrationnya nggak ya?

Kalau semisal nggak ada, sertain DDLnya ya, biar nanti bisa dipake untuk define databasenya di server BCC

**Comment by shafaalafghany** [comment]
Untuk migrationnya gk ada mas.

Oke baik, hbis ini saya sertain DDLnya mas

**Comment by afikrim** [comment]
Oke thanks ya

**Comment by shafaalafghany** [comment]
Permisi mas, kalo di dalam DDLnya ada yg berubah gimana ya ?

**Comment by afikrim** [comment]
Gapapa kalo berubah, asal nanti pas mau ngecreate table dikasih drop table if exists dulu, biar nggak error

**Comment by shafaalafghany** [comment]
Ini mau nambahin table sama nambahin relasi sih mas, kira2 aman gk mas ?

**Comment by afikrim** [comment]
Coba aja dulu di local, kalo semisal di local nggak error, di server kemungkinan juga nggak
